export const colors = {
  primaryDark: '#2d3436',
  primaryLight: '#dfe6e9',
  primaryBlue: '#0984e3',
  darkBlue: '#1e3799',
  primaryGreen: '#317174',
  primaryTeal: '#0fb9b1',
  primaryGrey: '#d1d8e0',
  primaryGray: '#7f8fa6',
} as const;

export const dictionary = {
  companyTitle: 'Imobil Online',
  apartment: 'Apartament',
  apartments: 'Apartamente',
  house: 'Casă',
  houses: 'Case',
  commercialSpaces: 'Spații comerciale',
  land: 'Terenuri',
  aboutUs1:
    'Oferim asistență profesională pe tot parcursul tranzacției de vânzare/cumpărare sau chirie a unui imobil, astfel găsim soluții optime pentru orice situație.',
  mainTitle: 'Apartamente/case/terenuri în orașe și suburbii',
  mainText: 'Comision zero, pentru cumpărători și chiriași',
  sortBy: 'Sortează după',
  newestByDate: 'Dată cele mai noi',
  moreExpensive: 'Preț mai scump',
  lessExpensive: 'Preț mai ieftin',
  filter: 'Filtru',
  subscribe: 'Abonează-te',
  typeOfBuilding: 'Tip cladire',
  newKindOfBuilding: 'Bloc nou',
  oldKindOfBuilding: 'Bloc vechi',
  numberOfRooms: 'Număr de camere',
  realEstateState: 'Stare imobil',
  euroRepair: 'Reparație euro',
  medium: 'Medie',
  noRepair: 'Fără reparație',
  underConstruction: 'În construcție',
  applyFilter: 'Aplică filtru',
} as const;
